package ga.cyber241.mbolopass.notification;

public enum NotificationType {
  MEDICAL_ACCESS_REQUEST_RECEIVED,
  MEDICAL_ACCESS_REQUEST_APPROVED,
  MEDICAL_ACCESS_REQUEST_DENIED,
  MEDICAL_ACCESS_CODE_GENERATED,
  MEDICAL_ACCESS_ACTIVATED,
  MEDICAL_ACCESS_REVOKED,
  MEDICAL_ACCESS_EXPIRING,
  MEDICAL_ACCESS_EXPIRED
}
